spring:
  application:
    name: "cosmocats"
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        jdbc.batch_size: 15
        order_inserts: true
        order_updates: true
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmocats
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: cosmocats-pool
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080

feature:
  cosmo-cats:
    enabled: true
  kitty-products:
    enabled: false

logging:
  level:
    org.springframework: INFO
    liquibase: INFO
    org.hibernate: INFO